"SELECT m.movieid,array_to_string(array_agg(distinct md.title),',') AS title, "
                    + "array_to_string(array_agg(distinct md.genre),',') AS genres, "
                    + "array_to_string(array_agg(distinct a.name),',') AS actors, "
                    + "MAX(movie_runtime(run.time)), "
                    + "MAX(movie_year(m.year)), "
                    + "MAX(rank.rank::float) "
                    + "FROM moviedata md "
                    + "INNER JOIN runningtimes run ON md.movieid = run.movieid "
                    + "INNER JOIN ratings rank ON run.movieid = rank.movieid "
                    + "INNER JOIN genres genre ON rank.movieid = genre.movieid "
                    + "INNER JOIN movies m ON genre.movieid = m.movieid "
                    + "LEFT JOIN actors a ON md.actorid = a.actorid "
                    + "WHERE md.movieid IN ("
                    + "SELECT mm.movieid FROM moviedata mm "
                    + "LEFT JOIN actors aa ON mm.actorid = aa.actorid "
                    + "WHERE aa.name LIKE ANY(?)) "
                    + "AND movie_runtime(run.time) BETWEEN (?) AND (?) "
                    + "AND movie_year(m.year) BETWEEN (?) AND (?) "
                    + "AND(rank.rank::float BETWEEN (?) AND 10.0"
                    + "OR genre.genre = ANY(?)) "
                    + "AND md.title NOT LIKE '%(TV)' "
                    + "AND genre.genre NOT LIKE '%Documentary' "
                    + "GROUP BY m.movieid "
                    + "LIMIT 200";